const w: Record<string, string> = (window as any).__ENV__ || {};

export const config = {
  REACT_APP_API_BASE_URL: w.REACT_APP_API_BASE_URL ?? process.env.REACT_APP_API_BASE_URL ?? '',
  REACT_APP_API_PREFIX: w.REACT_APP_API_PREFIX ?? process.env.REACT_APP_API_PREFIX ?? '',
  REACT_APP_GIT_PREFIX: w.REACT_APP_GIT_PREFIX ?? process.env.REACT_APP_GIT_PREFIX ?? '',
  REACT_APP_AUTH_PREFIX: w.REACT_APP_AUTH_PREFIX ?? process.env.REACT_APP_AUTH_PREFIX ?? '',
  REACT_APP_VERSION_PREFIX: w.REACT_APP_VERSION_PREFIX ?? process.env.REACT_APP_VERSION_PREFIX ?? '',
  REACT_APP_RADAR_PREFIX: w.REACT_APP_RADAR_PREFIX ?? process.env.REACT_APP_RADAR_PREFIX ?? '',
  REACT_APP_ASSETS_PREFIX: w.REACT_APP_ASSETS_PREFIX ?? process.env.REACT_APP_ASSETS_PREFIX ?? '',
  REACT_APP_NOTEBOOK_PREFIX: w.REACT_APP_NOTEBOOK_PREFIX ?? process.env.REACT_APP_NOTEBOOK_PREFIX ?? '',
  REACT_APP_COLLABORATION_PREFIX: w.REACT_APP_COLLABORATION_PREFIX ?? process.env.REACT_APP_COLLABORATION_PREFIX ?? '',
  REACT_APP_PLATFORM_ENV: w.REACT_APP_PLATFORM_ENV ?? process.env.REACT_APP_PLATFORM_ENV ?? '',
  REACT_APP_IS_PRODUCTION: w.REACT_APP_IS_PRODUCTION ?? process.env.REACT_APP_IS_PRODUCTION ?? '',
  REACT_APP_POSTHOG_KEY: w.REACT_APP_POSTHOG_KEY ?? process.env.REACT_APP_POSTHOG_KEY ?? '',
  REACT_APP_SESSION_DEBUGGER_KEY: w.REACT_APP_SESSION_DEBUGGER_KEY ?? process.env.REACT_APP_SESSION_DEBUGGER_KEY ?? '',
  REACT_APP_SESSION_DEBUGGER_API_BASE_URL: w.REACT_APP_SESSION_DEBUGGER_API_BASE_URL ?? process.env.REACT_APP_SESSION_DEBUGGER_API_BASE_URL ?? '',
  REACT_APP_SESSION_DEBUGGER_EXPORTER_ENDPOINT: w.REACT_APP_SESSION_DEBUGGER_EXPORTER_ENDPOINT ?? process.env.REACT_APP_SESSION_DEBUGGER_EXPORTER_ENDPOINT ?? '',
  REACT_APP_SANDBOX_URL: w.REACT_APP_SANDBOX_URL ?? process.env.REACT_APP_SANDBOX_URL ?? '',
  REACT_APP_DEMO_PUBLIC: w.REACT_APP_DEMO_PUBLIC ?? process.env.REACT_APP_DEMO_PUBLIC ?? '',
  REACT_APP_STRIPE_DEFAULT_PRO_PRICE_ID: w.REACT_APP_STRIPE_DEFAULT_PRO_PRICE_ID ?? process.env.REACT_APP_STRIPE_DEFAULT_PRO_PRICE_ID ?? '',
  REACT_APP_STRIPE_FREE_PRODUCT_ID: w.REACT_APP_STRIPE_FREE_PRODUCT_ID ?? process.env.REACT_APP_STRIPE_FREE_PRODUCT_ID ?? '',
  REACT_APP_SERVICE_VERSION: w.REACT_APP_SERVICE_VERSION ?? process.env.REACT_APP_SERVICE_VERSION ?? '',
};
