export enum WorkspaceActions {
  CLEANUP = "CLEANUP",
  SET_WORKSPACE_ID = "SET_WORKSPACE_ID",
  SET_WORKSPACE_FETCHING = "SET_WORKSPACE_FETCHING",
  SET_WORKSPACE_FETCHED = "SET_WORKSPACE_FETCHED",
  SET_WORKSPACE_DATA = "SET_WORKSPACE_DATA",
  PUT_WORKSPACE_DATA = "PUT_WORKSPACE_DATA",
  SET_ACCOUNT_FETCHING = "SET_ACCOUNT_FETCHING",
  SET_ACCOUNT_FETCHED = "SET_ACCOUNT_FETCHED",
  SET_ACCOUNT_DATA = "SET_ACCOUNT_DATA",
  SET_TEAMS_FETCHING = "SET_TEAMS_FETCHING",
  SET_TEAMS_FETCHED = "SET_TEAMS_FETCHED",
  SET_TEAMS_DATA = "SET_TEAMS_DATA",
  SET_PROJECTS_FETCHING = "SET_PROJECTS_FETCHING",
  SET_PROJECTS_FETCHED = "SET_PROJECTS_FETCHED",
  SET_PROJECTS_DATA = "SET_PROJECTS_DATA",
  SET_USERS_FETCHING = "SET_USERS_FETCHING",
  SET_USERS_FETCHED = "SET_USERS_FETCHED",
  SET_USERS_DATA = "SET_USERS_DATA",
  SET_USER_FETCHING = "SET_USER_FETCHING",
  SET_USER_FETCHED = "SET_USER_FETCHED",
  SET_USER_DATA = "SET_USER_DATA",
}

export enum VersionActions {
  SET_BRANCHES_DATA = "SET_BRANCHES_DATA",
  SET_BRANCHES_FETCHED = "SET_BRANCHES_FETCHED",
  SET_BRANCHES_PARAMS = "SET_BRANCHES_PARAMS",
  SET_BRANCHES_FETCHING = "SET_BRANCHES_FETCHING",

  SET_DEFAULT_BRANCH_ID = "SET_DEFAULT_BRANCH_ID",
  SET_DEFAULT_BRANCH_DATA = "SET_DEFAULT_BRANCH_DATA",
  SET_DEFAULT_BRANCH_FETCHED = "SET_DEFAULT_BRANCH_FETCHED",
  SET_DEFAULT_BRANCH_FETCHING = "SET_DEFAULT_BRANCH_FETCHING",

  SET_CURRENT_BRANCH_ID = "SET_CURRENT_BRANCH_ID",
  SET_CURRENT_BRANCH_DATA = "SET_CURRENT_BRANCH_DATA",
  SET_CURRENT_BRANCH_FETCHED = "SET_CURRENT_BRANCH_FETCHED",
  SET_CURRENT_BRANCH_FETCHING = "SET_CURRENT_BRANCH_FETCHING",

  SET_CURRENT_BRANCH_REVIEWS_DATA = "SET_CURRENT_BRANCH_REVIEWS_DATA",
  SET_CURRENT_BRANCH_REVIEWS_FETCHED = "SET_CURRENT_BRANCH_REVIEWS_FETCHED",
  SET_CURRENT_BRANCH_REVIEWS_FETCHING = "SET_CURRENT_BRANCH_REVIEWS_FETCHING",
}

export enum PermissionActions {
  CLEANUP = "CLEANUP",
  SET_ROLES_FETCHING = "SET_ROLES_FETCHING",
  SET_ROLES_FETCHED = "SET_ROLES_FETCHED",
  SET_ROLES_DATA = "SET_ROLES_DATA",
  PUT_ROLES_DATA = "PUT_ROLES_DATA",
  SET_FEATURE_FLAGS_DATA = "SET_FEATURE_FLAGS_DATA",
  SET_PERMISSIONS_DATA = "SET_PERMISSIONS_DATA",
  SET_PERMISSIONS_FETCHING = "SET_PERMISSIONS_FETCHING",
  SET_PERMISSIONS_FETCHED = "SET_PERMISSIONS_FETCHED",
}
