# version: "2.4"

name: multiplayer-platform

x-default-network: &networks
  - default
  # - collector-netowrk

x-environment-variables: &environment-variables
  STRIPE_DISABLED: true
  MONGODB_ENCRYPTION_MASTER_KEY_PROVIDER: local
  MONGODB_URI: mongodb://mongo:27017/multiplayer
  AMQP_URI: amqp://rabbit:5672
  REDIS_URI: redis://redis:6379

  CLICKHOUSE_URI: http://clickhouse:8123
  KAFKA_URI: kafka:29092
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4317/v1/logs
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317/v1/traces
  OTEL_ENABLED: true
  PROMETHEUS_EXPORTER_ENABLED: true
  VERSION_SERVICE_URI: http://version:3006/v0/version
  INTERNAL_VERSION_SERVICE_URI: http://version:3006/internal/v0/version
  INTERNAL_GIT_SERVICE_URI: http://git:3007/internal/v0/git
  API_SERVICE_URI: http://api:3001/v0/api
  NEW_RELIC_ENABLED: false
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_REGION: us-east-1
  OPENSEARCH_URI: http://opensearch:9200
  S3_HOST: http://localhost:9000
  S3_EXPORT_HOST: http://minio:9000

x-service-dependencies: &service-dependencies
  mongo:
    condition: service_healthy
  rabbit:
    condition: service_healthy
  redis:
    condition: service_healthy
  minio:
    condition: service_healthy
  clickhouse:
    condition: service_healthy
  kafka:
    condition: service_healthy
  otel-collector:
    condition: service_healthy

services:
  # web-app:
  #   container_name: multiplayer-web-app
  #   build:
  #     context: ..
  #     dockerfile: clients/multiplayer-web-app/Dockerfile
  #   restart: on-failure
  #   environment:
  #     <<: *environment-variables
  #     REACT_APP_IS_PRODUCTION: true
  #     REACT_APP_SESSION_DEBUGGER_API_BASE_URL:
  #     REACT_APP_API_BASE_URL: localhost
  #     REACT_APP_API_PREFIX: /v0/api
  #     REACT_APP_GIT_PREFIX: /v0/git
  #     REACT_APP_AUTH_PREFIX: /v0/auth
  #     REACT_APP_RADAR_PREFIX: /v0/radar
  #     REACT_APP_ASSETS_PREFIX: /v0/assets
  #     REACT_APP_VERSION_PREFIX: /v0/version
  #     REACT_APP_COLLABORATION_PREFIX: /v0/collaboration
  #     REACT_APP_POSTHOG_KEY:
  #     REACT_APP_NEWRELIC_APPLICATION_ID:
  #     REACT_APP_NEWRELIC_ACCOUNT_ID:
  #     REACT_APP_PLATFORM_ENV: local
  #     REACT_APP_SESSION_DEBUGGER_KEY:
  #     REACT_APP_SANDBOX_URL:
  #     REACT_APP_DEMO_PUBLIC:
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   networks: *networks

  api:
    # container_name: multiplayer-api
    image: multiplayerapp/multiplayer-api:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3001
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/api
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on: *service-dependencies
    networks: *networks

  assets:
    # container_name: multiplayer-assets
    image: multiplayerapp/multiplayer-assets:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3009
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/assets
    env_file:
      - .env
    ports:
      - 3009:3009
    depends_on: *service-dependencies
    networks: *networks

  auth:
    # container_name: multiplayer-auth
    image: multiplayerapp/multiplayer-auth:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3002
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/auth
    env_file:
      - .env
    ports:
      - 3002:3002
    depends_on: *service-dependencies
    networks: *networks

  collaboration:
    # container_name: multiplayer-collaboration
    image: multiplayerapp/multiplayer-collaboration:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3003
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/collaboration
    env_file:
      - .env
    ports:
      - 3003:3003
    depends_on: *service-dependencies
    networks: *networks

  git:
    # container_name: multiplayer-git
    image: multiplayerapp/multiplayer-git:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3007
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/git
    env_file:
      - .env
    ports:
      - 3007:3007
    depends_on: *service-dependencies
    networks: *networks

  notification:
    # container_name: multiplayer-notification
    image: multiplayerapp/multiplayer-notification:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3005
      SWAGGER_ENABLED: true
    env_file:
      - .env
    ports:
      - 3005:3005
    depends_on: *service-dependencies
    networks: *networks

  radar:
    # container_name: multiplayer-radar
    image: multiplayerapp/multiplayer-radar:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 5318
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/radar
    env_file:
      - .env
    ports:
      - 5318:5318
    depends_on: *service-dependencies
    networks: *networks

  version:
    # container_name: multiplayer-version
    image: multiplayerapp/multiplayer-version:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3006
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/version
    env_file:
      - .env
    ports:
      - 3006:3006
    depends_on: *service-dependencies
    networks: *networks

  otel-collector:
    image: multiplayerapp/multiplayer-opentelemetry-collector-contrib:${MULTIPLAYER_COLLECTOR_RELEASE:-latest}
    platform: linux/amd64
    # container_name: multiplayer-otel-collector
    # hostname: multiplayer-otel-collector
    restart: on-failure
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:13133/health/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ../scripts/otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      #  - 4318:4318   # OTLP http receiver
      - 7318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      default:
        aliases:
          - multiplayer-otel-collector

  clickhouse:
    image: clickhouse/clickhouse-server:24.6.2.17-alpine
    # container_name: multiplayer-clickhouse
    # hostname: multiplayer-clickhouse
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 8000:8000
      - 8123:8123
    volumes:
      - multiplayer-clickhouse-data:/var/lib/clickhouse
      - multiplayer-clickhouse-logs:/var/log/clickhouse-server
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../scripts/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - multiplayer-clickhouse

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.2
    # container_name: multiplayer-zookeeper
    # hostname: multiplayer-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'echo > /dev/tcp/localhost/2181' 2>/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 2181:2181
    networks:
      default:
        aliases:
          - multiplayer-zookeeper

  kafka:
    image: bitnamilegacy/kafka:3.4.1
    # container_name: multiplayer-kafka
    # hostname: multiplayer-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'echo > /dev/tcp/localhost/9092' 2>/dev/null || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    ports:
      - 9092:9092
      - 29092:29092
    # volumes:
    #   - "multiplayer-kafka-data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://multiplayer-kafka:9092,EXTERNAL://multiplayer-kafka:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:a# version: "2.4"

name: multiplayer-platform

x-default-network: &networks
  - default
  # - collector-netowrk

x-environment-variables: &environment-variables
  STRIPE_DISABLED: true
  MONGODB_ENCRYPTION_MASTER_KEY_PROVIDER: local
  MONGODB_URI: mongodb://mongo:27017/multiplayer
  AMQP_URI: amqp://rabbit:5672
  REDIS_URI: redis://redis:6379

  CLICKHOUSE_URI: http://clickhouse:8123
  KAFKA_URI: kafka:29092
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4317/v1/logs
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317/v1/traces
  OTEL_ENABLED: true
  PROMETHEUS_EXPORTER_ENABLED: true
  VERSION_SERVICE_URI: http://version:3006/v0/version
  INTERNAL_VERSION_SERVICE_URI: http://version:3006/internal/v0/version
  INTERNAL_GIT_SERVICE_URI: http://git:3007/internal/v0/git
  API_SERVICE_URI: http://api:3001/v0/api
  NEW_RELIC_ENABLED: false
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_REGION: us-east-1
  OPENSEARCH_URI: http://opensearch:9200
  S3_HOST: http://localhost:9000
  S3_EXPORT_HOST: http://minio:9000

x-service-dependencies: &service-dependencies
  mongo:
    condition: service_healthy
  rabbit:
    condition: service_healthy
  redis:
    condition: service_healthy
  minio:
    condition: service_healthy
  clickhouse:
    condition: service_healthy
  kafka:
    condition: service_healthy
  otel-collector:
    condition: service_healthy

services:
  # web-app:
  #   container_name: multiplayer-web-app
  #   build:
  #     context: ..
  #     dockerfile: clients/multiplayer-web-app/Dockerfile
  #   restart: on-failure
  #   environment:
  #     <<: *environment-variables
  #     REACT_APP_IS_PRODUCTION: true
  #     REACT_APP_SESSION_DEBUGGER_API_BASE_URL:
  #     REACT_APP_API_BASE_URL: localhost
  #     REACT_APP_API_PREFIX: /v0/api
  #     REACT_APP_GIT_PREFIX: /v0/git
  #     REACT_APP_AUTH_PREFIX: /v0/auth
  #     REACT_APP_RADAR_PREFIX: /v0/radar
  #     REACT_APP_ASSETS_PREFIX: /v0/assets
  #     REACT_APP_VERSION_PREFIX: /v0/version
  #     REACT_APP_COLLABORATION_PREFIX: /v0/collaboration
  #     REACT_APP_POSTHOG_KEY:
  #     REACT_APP_NEWRELIC_APPLICATION_ID:
  #     REACT_APP_NEWRELIC_ACCOUNT_ID:
  #     REACT_APP_PLATFORM_ENV: local
  #     REACT_APP_SESSION_DEBUGGER_KEY:
  #     REACT_APP_SANDBOX_URL:
  #     REACT_APP_DEMO_PUBLIC:
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   networks: *networks

  api:
    # container_name: multiplayer-api
    image: multiplayerapp/multiplayer-api:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3001
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/api
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on: *service-dependencies
    networks: *networks

  assets:
    # container_name: multiplayer-assets
    image: multiplayerapp/multiplayer-assets:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3009
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/assets
    env_file:
      - .env
    ports:
      - 3009:3009
    depends_on: *service-dependencies
    networks: *networks

  auth:
    # container_name: multiplayer-auth
    image: multiplayerapp/multiplayer-auth:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3002
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/auth
    env_file:
      - .env
    ports:
      - 3002:3002
    depends_on: *service-dependencies
    networks: *networks

  collaboration:
    # container_name: multiplayer-collaboration
    image: multiplayerapp/multiplayer-collaboration:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3003
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/collaboration
    env_file:
      - .env
    ports:
      - 3003:3003
    depends_on: *service-dependencies
    networks: *networks

  git:
    # container_name: multiplayer-git
    image: multiplayerapp/multiplayer-git:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3007
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/git
    env_file:
      - .env
    ports:
      - 3007:3007
    depends_on: *service-dependencies
    networks: *networks

  notification:
    # container_name: multiplayer-notification
    image: multiplayerapp/multiplayer-notification:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3005
      SWAGGER_ENABLED: true
    env_file:
      - .env
    ports:
      - 3005:3005
    depends_on: *service-dependencies
    networks: *networks

  radar:
    # container_name: multiplayer-radar
    image: multiplayerapp/multiplayer-radar:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 5318
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/radar
    env_file:
      - .env
    ports:
      - 5318:5318
    depends_on: *service-dependencies
    networks: *networks

  version:
    # container_name: multiplayer-version
    image: multiplayerapp/multiplayer-version:${MULTIPLAYER_RELEASE:-latest}
    platform: linux/amd64
    restart: on-failure
    environment:
      <<: *environment-variables
      PORT: 3006
      SWAGGER_ENABLED: true
      API_PREFIX: /v0/version
    env_file:
      - .env
    ports:
      - 3006:3006
    depends_on: *service-dependencies
    networks: *networks

  otel-collector:
    image: multiplayerapp/multiplayer-opentelemetry-collector-contrib:${MULTIPLAYER_COLLECTOR_RELEASE:-latest}
    platform: linux/amd64
    # container_name: multiplayer-otel-collector
    # hostname: multiplayer-otel-collector
    restart: on-failure
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:13133/health/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ../scripts/otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      #  - 4318:4318   # OTLP http receiver
      - 7318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      default:
        aliases:
          - multiplayer-otel-collector

  clickhouse:
    image: clickhouse/clickhouse-server:24.6.2.17-alpine
    # container_name: multiplayer-clickhouse
    # hostname: multiplayer-clickhouse
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 8000:8000
      - 8123:8123
    volumes:
      - multiplayer-clickhouse-data:/var/lib/clickhouse
      - multiplayer-clickhouse-logs:/var/log/clickhouse-server
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../scripts/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - multiplayer-clickhouse

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.2
    # container_name: multiplayer-zookeeper
    # hostname: multiplayer-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'echo > /dev/tcp/localhost/2181' 2>/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 2181:2181
    networks:
      default:
        aliases:
          - multiplayer-zookeeper

  kafka:
    image: bitnamilegacy/kafka:3.4.1
    # container_name: multiplayer-kafka
    # hostname: multiplayer-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'echo > /dev/tcp/localhost/9092' 2>/dev/null || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    ports:
      - 9092:9092
      - 29092:29092
    # volumes:
    #   - "multiplayer-kafka-data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://multiplayer-kafka:9092,EXTERNAL://multiplayer-kafka:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      default:
        aliases:
          - multiplayer-kafka

  opensearch:
    image: opensearchproject/opensearch:latest
    # container_name: multiplayer-opensearch
    # hostname: multiplayer-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=El3ph@nt___123
    volumes:
      - opensearch-data:/data/opensearch
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      default:
        aliases:
          - multiplayer-opensearch

  nginx:
    image: nginx:latest
    # container_name: multiplayer-nginx
    # hostname: multiplayer-nginx
    restart: on-failure
    volumes:
      - ../scripts/nginx.conf:/etc/nginx/conf.d/node.template
    ports:
      - "80:80"
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks: *networks

  mongo:
    image: mongo:8.0.0
    # container_name: multiplayer-mongo
    # hostname: multiplayer-mongo
    restart: on-failure
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - 27017-27020:27017-27020
      - 30000:30000
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=multiplayer
    volumes:
      - multiplayer-mongo-data:/data/db
    networks:
      default:
        aliases:
          - multiplayer-mongo

  rabbit:
    image: rabbitmq:3.10-management
    # container_name: multiplayer-rabbit
    # hostname: multiplayer-rabbit
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - multiplayer-rabbit-data:/var/lib/rabbitmq/mnesia/
    # env_file:
    #   - ../scripts/.env.rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
        aliases:
          - multiplayer-rabbit

  redis:
    image: redis:alpine
    # container_name: multiplayer-redis
    # hostname: multiplayer-redis
    command: redis-server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - multiplayer-redis

  minio:
    image: quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z
    # container_name: multiplayer-minio
    # hostname: multiplayer-minio
    restart: on-failure
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_REGION_NAME=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - multiplayer-minio-data:/data
    networks:
      default:
        aliases:
          - multiplayer-minio

  createbuckets:
    # container_name: multiplayer-minio-createbuckets
    image: minio/mc
    restart: on-failure
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://multiplayer-minio:9000 minioadmin minioadmin;

      /usr/bin/mc mb myminio/public-bucket;
      /usr/bin/mc anonymous set public myminio/public-bucket;

      /usr/bin/mc mb myminio/private-bucket;
      /usr/bin/mc anonymous set public myminio/private-bucket;

      /usr/bin/mc mb myminio/debug-sessions-bucket;
      /usr/bin/mc anonymous set public myminio/debug-sessions-bucket;

      exit 0;
      "
    networks: *networks

volumes:
  multiplayer-mongo-data:
  multiplayer-mongocryptd-data:
  multiplayer-rabbit-data:
  multiplayer-minio-data:
  multiplayer-redis-ui-data:
  multiplayer-clickhouse-logs:
  multiplayer-clickhouse-data:
  opensearch-data:
  # multiplayer-kafka-data:
  # multiplayer-elasticsearch-data:
  #   driver: local

      default:
        aliases:
          - multiplayer-kafka

  opensearch:
    image: opensearchproject/opensearch:latest
    # container_name: multiplayer-opensearch
    # hostname: multiplayer-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=El3ph@nt___123
    volumes:
      - opensearch-data:/data/opensearch
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      default:
        aliases:
          - multiplayer-opensearch

  nginx:
    image: nginx:latest
    # container_name: multiplayer-nginx
    # hostname: multiplayer-nginx
    restart: on-failure
    volumes:
      - ../scripts/nginx.conf:/etc/nginx/conf.d/node.template
    ports:
      - "80:80"
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks: *networks

  mongo:
    image: mongo:8.0.0
    # container_name: multiplayer-mongo
    # hostname: multiplayer-mongo
    restart: on-failure
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - 27017-27020:27017-27020
      - 30000:30000
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=multiplayer
    volumes:
      - multiplayer-mongo-data:/data/db
    networks:
      default:
        aliases:
          - multiplayer-mongo

  rabbit:
    image: rabbitmq:3.10-management
    # container_name: multiplayer-rabbit
    # hostname: multiplayer-rabbit
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - multiplayer-rabbit-data:/var/lib/rabbitmq/mnesia/
    # env_file:
    #   - ../scripts/.env.rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
        aliases:
          - multiplayer-rabbit

  redis:
    image: redis:alpine
    # container_name: multiplayer-redis
    # hostname: multiplayer-redis
    command: redis-server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - multiplayer-redis

  minio:
    image: quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z
    # container_name: multiplayer-minio
    # hostname: multiplayer-minio
    restart: on-failure
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_REGION_NAME=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - multiplayer-minio-data:/data
    networks:
      default:
        aliases:
          - multiplayer-minio

  createbuckets:
    # container_name: multiplayer-minio-createbuckets
    image: minio/mc
    restart: on-failure
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://multiplayer-minio:9000 minioadmin minioadmin;

      /usr/bin/mc mb myminio/public-bucket;
      /usr/bin/mc anonymous set public myminio/public-bucket;

      /usr/bin/mc mb myminio/private-bucket;
      /usr/bin/mc anonymous set public myminio/private-bucket;

      /usr/bin/mc mb myminio/debug-sessions-bucket;
      /usr/bin/mc anonymous set public myminio/debug-sessions-bucket;

      exit 0;
      "
    networks: *networks

volumes:
  multiplayer-mongo-data:
  multiplayer-mongocryptd-data:
  multiplayer-rabbit-data:
  multiplayer-minio-data:
  multiplayer-redis-ui-data:
  multiplayer-clickhouse-logs:
  multiplayer-clickhouse-data:
  opensearch-data:
  # multiplayer-kafka-data:
  # multiplayer-elasticsearch-data:
  #   driver: local
