# version: "2.4"

name: multiplayer-platform-dev

x-default-network: &networks
  - default
  # - collector-netowrk

# networks:
#   collector-netowrk:
#     name: collector-netowrk
#     external: true

services:
  nginx:
    image: nginx:latest
    # container_name: multiplayer-nginx
    # hostname: multiplayer-nginx
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../scripts/nginx.conf:/etc/nginx/conf.d/node.template
    ports:
      - "80:80"
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks: *networks

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    # container_name: multiplayer-jaeger
    # hostname: multiplayer-jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - 6317:4317 # grpc receiver
      # - "4318:4318"   # OTLP http receiver
      - 6318:4318 # OTLP http receiver
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
    networks: *networks

  mongo:
    image: mongo:8.0.0
    # container_name: multiplayer-mongo
    # hostname: multiplayer-mongo
    restart: on-failure
    ports:
      - 27017-27020:27017-27020
      - 30000:30000
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=multiplayer
    volumes:
      - multiplayer-mongo-data:/data/db
    networks: *networks

  # mongocryptd:
  #     image: local-mongocryptd
  #     container_name: mongocryptd
  #     entrypoint: mongocryptd
  #     restart: on-failure
  #     tty: true
  #     volumes:
  #       - multiplayer-mongocryptd-data:/data/db

  rabbit:
    image: rabbitmq:3.10-management
    # container_name: multiplayer-rabbit
    # hostname: multiplayer-rabbit
    restart: on-failure
    volumes:
      - multiplayer-rabbit-data:/var/lib/rabbitmq/mnesia/
    # env_file:
    #   - ../scripts/.env.rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks: *networks

  redis:
    image: redis:alpine
    # container_name: multiplayer-redis
    # hostname: multiplayer-redis
    command: redis-server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    networks: *networks

  # redis-ui:
  #   container_name: multiplayer-redis-ui
  #   hostname: multiplayer-redis-ui
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - 8001:8001 # http://localhost:8001
  #   volumes:
  #     - multiplayer-redis-ui-data:/db

  minio:
    image: quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z
    # container_name: multiplayer-minio
    # hostname: multiplayer-minio
    restart: on-failure
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_REGION_NAME=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - multiplayer-minio-data:/data
    networks: *networks

  createbuckets:
    # container_name: multiplayer-minio-createbuckets
    image: minio/mc
    restart: on-failure
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://multiplayer-minio:9000 minioadmin minioadmin;

      /usr/bin/mc mb myminio/public-bucket;
      /usr/bin/mc anonymous set public myminio/public-bucket;

      /usr/bin/mc mb myminio/private-bucket;
      /usr/bin/mc anonymous set public myminio/private-bucket;

      /usr/bin/mc mb myminio/debug-sessions-bucket;
      /usr/bin/mc anonymous set public myminio/debug-sessions-bucket;

      exit 0;
      "
    networks: *networks

  # elasticsearch:
  #   hostname: multiplayer-elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  #   container_name: multiplayer-elasticsearch
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - multiplayer-elasticsearch-data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300

  # api:
  #   container_name: multiplayer-api
  #   image: docker.io/local/api:master
  #   restart: on-failure
  #   environment:
  #     - PORT=3001
  #     - SWAGGER_ENABLED=true
  #     - API_PREFIX=/v0/api
  #     - MONGODB_ENCRYPTION_MASTER_KEY_PROVIDER=local
  #     - MONGODB_URI=mongodb://multiplayer-mongo:27017/multiplayer
  #     - AMQP_URI=amqp://multiplayer-rabbit:5672
  # - REDIS_URI=redis://localhost:6379

  otel-collector:
    image: multiplayerapp/multiplayer-opentelemetry-collector-contrib:${OTEL_COLLECTOR_RELEASE_TAG:-latest}
    # container_name: multiplayer-otel-collector
    # hostname: multiplayer-otel-collector
    restart: on-failure
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - kafka
    volumes:
      - ../scripts/otel-collector-config-dev.yaml:/etc/otel/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      #  - 4318:4318   # OTLP http receiver
      - 7318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks: *networks

  clickhouse:
    image: clickhouse/clickhouse-server:24.6.2.17-alpine
    # container_name: multiplayer-clickhouse
    # hostname: multiplayer-clickhouse
    restart: on-failure
    ports:
      - 8000:9000
      - 8123:8123
    volumes:
      - multiplayer-clickhouse-data:/var/lib/clickhouse
      - multiplayer-clickhouse-logs:/var/log/clickhouse-server
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ../scripts/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../scripts/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks: *networks

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.2
    # container_name: multiplayer-zookeeper
    # hostname: multiplayer-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181
    networks: *networks

  kafka:
    image: bitnamilegacy/kafka:3.4.1
    # container_name: multiplayer-kafka
    # hostname: multiplayer-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    # volumes:
    #   - "multiplayer-kafka-data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: *networks

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: multiplayer-kafka-ui
  #   hostname: multiplayer-kafka-ui
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - kafka
  #     # - kafka1
  #     # - schemaregistry0
  #     # - schemaregistry1
  #     # - kafka-connect0
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: multiplayer-kafka:9092
  #     KAFKA_CLUSTERS_0_METRICS_PORT: 9997
  #     # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
  #     # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
  #     # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
  #     # KAFKA_CLUSTERS_1_NAME: secondLocal
  #     # KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1:29092
  #     # KAFKA_CLUSTERS_1_METRICS_PORT: 9998
  #     # KAFKA_CLUSTERS_1_SCHEMAREGISTRY: http://schemaregistry1:8085
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   networks: *networks
  opensearch:
    image: opensearchproject/opensearch:latest
    # hostname: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=El3ph@nt___123
    volumes:
      - opensearch-data:/data/opensearch
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

volumes:
  multiplayer-mongo-data:
  multiplayer-mongocryptd-data:
  multiplayer-rabbit-data:
  multiplayer-minio-data:
  multiplayer-redis-ui-data:
  multiplayer-clickhouse-logs:
  multiplayer-clickhouse-data:
  opensearch-data:
  # multiplayer-kafka-data:
  # multiplayer-elasticsearch-data:
  #   driver: local
