extensions:
  jwtauth:
    secret: "some_secret"
    attribute: Authorization
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "0.0.0.0:13133"
      status:
        enabled: true
        path: "/health/status"
      config:
        enabled: true
        path: "/health/config"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: jwtauth
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
        auth:
          authenticator: jwtauth

processors:
  transform/set_trace_type:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(resource.attributes["multiplayer.trace_type"], Substring(trace_id.string, 0, 6))
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["multiplayer.trace_type"], Substring(trace_id.string, 0, 6))

  transform/set_client_id:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(resource.attributes["multiplayer.session.client.id"], Substring(trace_id.string, 6, 8))
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["multiplayer.session.client.id"], Substring(trace_id.string, 6, 8))

  transform/set_session_id:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(resource.attributes["multiplayer.session.id"], Substring(trace_id.string, 6, 8))
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["multiplayer.session.id"], Substring(trace_id.string, 6, 8))

  groupbytrace:
    wait_duration: 10s
    num_traces: 1000
    num_workers: 2

  transform/add_resource_from_attributes:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(resource.attributes["multiplayer.workspace.id"], attributes["multiplayer.workspace.id"])
          - set(resource.attributes["multiplayer.project.id"], attributes["multiplayer.project.id"])
          - set(resource.attributes["multiplayer.integration.id"], attributes["multiplayer.integration.id"])
          - set(resource.attributes["multiplayer.session.client.id"], attributes["multiplayer.session.client.id"])

  attributes/from_auth_context:
    actions:
      - key: multiplayer.workspace.id
        from_context: auth.workspace
        action: insert
      - key: multiplayer.project.id
        from_context: auth.project
        action: insert
      - key: multiplayer.integration.id
        from_context: auth.integration
        action: insert

  batch:
    send_batch_size: 5
    send_batch_max_size: 5
    timeout: 3s

  size:

  memory_limiter/debdeb:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/d0cd0c:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/cdbcdb:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/error:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/cdbcac:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/debcdb:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  filter/debdeb:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "debdeb"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"
    logs:
      log_record:
        - attributes["log.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "debdeb"

  filter/d0cd0c:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "d0cd0c"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"

  filter/cdbcdb:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "cdbcdb"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"
    logs:
      log_record:
        - attributes["log.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "cdbcdb"

  filter/not-d0c:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] == "d0cd0c"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"

  filter/error:
    error_mode: ignore
    traces:
      span:
        - status.code != STATUS_CODE_ERROR and (attributes["exception.type"] == nil or attributes["exception.message"] == nil)

  filter/cdbcac:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "cdbcac"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"
    logs:
      log_record:
        - attributes["log.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "cdbcac"

  filter/debcdb:
    error_mode: ignore
    traces:
      span:
        - attributes["span.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "debcdb"
        - attributes["http.target"] == "/jaeger/v1/traces"
        - attributes["http.target"] == "/v1/traces"
        - attributes["http.target"] == "/v1/logs"
        - attributes["http.route"] == "/health"
        - attributes["http.route"] == "/healthz"
    logs:
      log_record:
        - attributes["log.size"] > 1000000
        - resource.attributes["multiplayer.trace_type"] != "debcdb"

  probabilistic_sampler:
    sampling_percentage: 1

  attributes/rename_debug_session_attr:
    actions:
      - key: multiplayer.session.id
        action: insert
        from_attribute: multiplayer.debug_session._id

exporters:
  kafka/d0c:
    brokers:
      - multiplayer-kafka:9092
    protocol_version: 2.0.0
    partition_traces_by_id: true
    traces:
      encoding: otlp_json
      topic: otlp_spans_d0c

  kafka/deb:
    brokers:
      - multiplayer-kafka:9092
    protocol_version: 2.0.0
    partition_traces_by_id: true
    traces:
      encoding: otlp_json
      topic: otlp_spans_deb
    logs:
      encoding: otlp_json
      topic: otlp_logs_deb

  kafka/cdb:
    brokers:
      - multiplayer-kafka:9092
    protocol_version: 2.0.0
    partition_traces_by_id: true
    traces:
      encoding: otlp_json
      topic: otlp_spans_cdb
    logs:
      encoding: otlp_json
      topic: otlp_logs_cdb

  kafka/error:
    brokers:
      - multiplayer-kafka:9092
    protocol_version: 2.0.0
    partition_traces_by_id: true
    traces:
      encoding: otlp_json
      topic: otlp_spans_error

service:
  telemetry:
    # traces:
    #   processors:
    #     - batch:
    #         exporter:
    #           otlp:
    #             protocol: http/protobuf
    #             endpoint: http://localhost:6318

    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888

  extensions: [healthcheckv2, jwtauth]
  pipelines:
    traces/debdeb:
      receivers: [otlp]
      processors:
        - size
        - transform/set_trace_type
        - filter/debdeb
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/debdeb
        - resourcedetection/system
        - batch
      exporters: [kafka/deb]

    logs/debdeb:
      receivers: [otlp]
      processors:
        - size
        - attributes/rename_debug_session_attr
        - transform/set_trace_type
        - filter/debdeb
        - transform/set_session_id
        - attributes/from_auth_context
        - memory_limiter/debdeb
        - resourcedetection/system
        - batch
      exporters: [kafka/deb]

    traces/cdbcdb:
      receivers: [otlp]
      processors:
        - size
        - attributes/rename_debug_session_attr
        - transform/set_trace_type
        - filter/cdbcdb
        - transform/set_session_id
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/cdbcdb
        - resourcedetection/system
        - batch
      exporters: [kafka/cdb]

    logs/cdbcdb:
      receivers: [otlp]
      processors:
        - size
        - attributes/rename_debug_session_attr
        - transform/set_trace_type
        - filter/cdbcdb
        - attributes/from_auth_context
        - memory_limiter/cdbcdb
        - resourcedetection/system
        - batch
      exporters: [kafka/cdb]

    traces/cdbcac:
      receivers: [otlp]
      processors:
        - size
        - transform/set_trace_type
        - filter/cdbcac
        - transform/set_client_id
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/cdbcac
        - resourcedetection/system
        - batch
      exporters: [kafka/deb]

    traces/debcdb:
      receivers: [otlp]
      processors:
        - size
        - transform/set_trace_type
        - filter/debcdb
        - transform/set_client_id
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/debcdb
        - resourcedetection/system
        - batch
      exporters: [kafka/deb]

    traces/d0cd0c:
      receivers: [otlp]
      processors:
        - size
        - attributes/rename_debug_session_attr
        - transform/set_trace_type
        - filter/d0cd0c
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        # - memory_limiter/d0cd0c
        - resourcedetection/system
        - batch
      exporters: [kafka/d0c]

    traces/random-d0c:
      receivers: [otlp]
      processors:
        - size
        - attributes/rename_debug_session_attr
        - transform/set_trace_type
        - filter/not-d0c
        - probabilistic_sampler
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/d0cd0c
        - resourcedetection/system
        - batch
      exporters: [kafka/d0c]

    traces/error:
      receivers: [otlp]
      processors:
        - size
        - filter/error
        - transform/set_client_id
        - attributes/from_auth_context
        - transform/add_resource_from_attributes
        - memory_limiter/error
        - resourcedetection/system
        - batch
      exporters: [kafka/error]
